language: php

php:
    - 7.1
    - 7.2

env:
    - SYMFONY_VERSION="3.4.*"
    - SYMFONY_VERSION="4.1.*"

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer require symfony/dependency-injection:${SYMFONY_VERSION} --no-update --no-interaction
    - composer update --prefer-dist --no-interaction

script:
    - composer validate --strict

    - vendor/bin/phpspec run --format dot -vvv --no-interaction
    - vendor/bin/behat --strict -vvv --no-interaction
